config/routes.rb
Photostream::Application.routes.draw do
   root :to => 'images#index'

   resources :images
end

app/models/image.rb
class Image < ActiveRecord::Base
   attr_accessible :title, :url, :author, :image, :remote_image_url

   validates :title, :presence => true

   mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

   def index
      @images = Image.order("title").page(params[:page]).per(5)
   end

   def new
      @image = Image.new
   end

   def create
      @image = Image.new(params[:image])
      if @image.save
         redirect_to images_path
      else 
         flash[:error] = "Could not create image!"
         render :new
      end 
   end

   def show
      @image = Image.find(params[:id])
   end

   def edit
      @image = Image.find(params[:id])
   end

   def update
      @image = Image.find(params[:id])
      if @image.update_attributes(params[:image])
         redirect_to @image
      else
         flash[:error] = "Could not update image."
         render :edit
      end
   end

   def destroy
      @image = Image.find(params[:id])
      @image.destroy
      redirect_to images_path
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= form_for @image do|f| %>
<div class='error'>
   <%= flash[:error] %>
</div>
<p>
   <%= f.label :title, "Enter Title" %>
   <%= @image.errors[:title].join(',') %>
   <%= f.text_field :title %>
</p>
<p>
   <%= f.label :remote_image_url, "Enter Image URL from web" %>
   <%= @image.errors[:remote_image_url].join(',') %>
   <%= f.text_field :remote_image_url %>
</p>
<p>
   <%= f.label :author, "Enter Original Author" %>
   <%= f.text_field :author  %>
</p>
<p>
   <%= f.submit "Save" %>
</p>
<% end %>

app/views/images/edit.html.erb
<h2>Edit <%= @image.title%></h2>
<%= render :partial => "form" %>
<%= image_tag @image.image.url %>

app/views/images/index.html.erb
<div class="row">
<%- @images.each do |image| %>
<div class="image half">
   <h2><%= image.title %></h2>
   <%= link_to image_path(image) do %>
      <%= image_tag image.image.url %>
   <% end %>
</div>
<% end %>
</div>
<%= paginate @images %>

app/views/images/new.html.erb
<h1>Add a New Image!</h1>

<%= render :partial => "form" %>

app/views/images/show.html.erb
<div class=<h2><%= @image.title %></h2>
<div class=".width-100 centered">
   <%= image_tag @image.image %>
</div>
<div class="third">
   <%= link_to "Edit", edit_image_path(@image) %>
   <%= link_to "Delete", @image, :method => :delete, :confirm => "You're about to delete this image. Are you sure?" %>
</div>
<h3> <%= @image.author %> </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photostream</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
 
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="nav-h">
      <ul>
         <li><a href=<%=images_path%>><i class="icon-th-list icon-4x"></i></a></li>
         <li><a href=<%=new_image_path%>><i class="icon-plus icon-4x"></i></a></li>
      </ul>
   </div>

   <div class = "container">

      <%= yield %>

  </div>
</body>
</html>